/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SidebarWrapperRouteRouteImport } from './routes/_sidebarWrapper/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidebarWrapperHomeRouteRouteImport } from './routes/_sidebarWrapper/home/route'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SidebarWrapperProfileUserIdRouteImport } from './routes/_sidebarWrapper/profile.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarWrapperRouteRoute = SidebarWrapperRouteRouteImport.update({
  id: '/_sidebarWrapper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarWrapperHomeRouteRoute = SidebarWrapperHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SidebarWrapperRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarWrapperProfileUserIdRoute =
  SidebarWrapperProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => SidebarWrapperRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/home': typeof SidebarWrapperHomeRouteRoute
  '/profile/$userId': typeof SidebarWrapperProfileUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/home': typeof SidebarWrapperHomeRouteRoute
  '/profile/$userId': typeof SidebarWrapperProfileUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebarWrapper': typeof SidebarWrapperRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/_sidebarWrapper/home': typeof SidebarWrapperHomeRouteRoute
  '/_sidebarWrapper/profile/$userId': typeof SidebarWrapperProfileUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/home'
    | '/profile/$userId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/home'
    | '/profile/$userId'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_sidebarWrapper'
    | '/dashboard'
    | '/login'
    | '/_sidebarWrapper/home'
    | '/_sidebarWrapper/profile/$userId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarWrapperRouteRoute: typeof SidebarWrapperRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarWrapper': {
      id: '/_sidebarWrapper'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarWrapperRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarWrapper/home': {
      id: '/_sidebarWrapper/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SidebarWrapperHomeRouteRouteImport
      parentRoute: typeof SidebarWrapperRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarWrapper/profile/$userId': {
      id: '/_sidebarWrapper/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof SidebarWrapperProfileUserIdRouteImport
      parentRoute: typeof SidebarWrapperRouteRoute
    }
  }
}

interface SidebarWrapperRouteRouteChildren {
  SidebarWrapperHomeRouteRoute: typeof SidebarWrapperHomeRouteRoute
  SidebarWrapperProfileUserIdRoute: typeof SidebarWrapperProfileUserIdRoute
}

const SidebarWrapperRouteRouteChildren: SidebarWrapperRouteRouteChildren = {
  SidebarWrapperHomeRouteRoute: SidebarWrapperHomeRouteRoute,
  SidebarWrapperProfileUserIdRoute: SidebarWrapperProfileUserIdRoute,
}

const SidebarWrapperRouteRouteWithChildren =
  SidebarWrapperRouteRoute._addFileChildren(SidebarWrapperRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarWrapperRouteRoute: SidebarWrapperRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
